### ISSUE TITLE
README.md: instructions for macOS - installer.sh requires configuration variables to be set

### ISSUE THREAD

**Issue by drjasonharrison** [angela-d/wifi-network-testing#1]
Based on the README I wasn't sure exactly how to install this for macOS
I cloned the repo.
I sort of thought that the installer.sh script would install stuff, but unfortunately it requires configuration variables to be setup.

On MacOS it looks like I should:
```
mkdir -p ~/.nettest
cp config-template.conf ~/.nettest/config.conf
./nettest.sh
```

and follow the prompts.

**Comment by angela-d** [comment]
This is a bug, I'll fix this shortly, too.

**Comment by angela-d** [comment]
I think I fixed this in the initial release, it's auto created by this block:
```bash
# check for config file
if [ ! -f ~/.nettest/config.conf ];
then
  [ "$ConfigTemplateLocation" == "" ] && echo -e "Config appears to be missing. Install a new version for bugfixes!\nIf this is a home install, run like so: /path/to/nettest.sh setup" && exit
  # add default configs if its not found
  mkdir -p ~/.nettest
  cp "$ConfigTemplateLocation/config-template.conf" ~/.nettest/config.conf
  echo "INSTALLPATH=$ConfigTemplateLocation" >> ~/.nettest/config.conf

  # now call it
  source ~/.nettest/config.conf
else
  # pull the config into the application
  source ~/.nettest/config.conf
fi
```

Can you point me where in the readme/wiki the setup wasn't clear?

On first run (assuming this is a home setup), it should be as follows:
```bash
/path/to/nettest.sh setup
```
Referenced in the wiki: https://github.com/angela-d/wifi-network-testing/wiki/Home-Install

If you were looking somewhere else, please point me to it (or feel free to modify it and send a PR)

**Comment by angela-d** [comment]
@drjasonharrison I believe there may have been confusion with installer.sh

I removed that component and I'll work on a standalone .app for Macs in lieu of at portion (time permitting), as something like that would likely be used more commonly than a git repo by most third-party multi-client scenarios.

When you've got time, do a fresh pull, it should make more sense.

I've also updated the wiki to be more clear about setup & first run:
https://github.com/angela-d/wifi-network-testing/wiki/First-Run

**Comment by drjasonharrison** [comment]
Thank you. I didn't notice the wiki before. I'm a "put it all in the gti repo" type of person rather than "git and wiki" type of person.
