### ISSUE TITLE
Possible shell error when doing a basic scan

### ISSUE THREAD

**Issue by drjasonharrison** [angela-d/wifi-network-testing#2]
I copied the default configuration into ~/.nettest/config.conf and ran nettest.sh twice, once to install on macOS, the second to run a scan. I selected (1) - basic scan.

Part of the output included 
```
 -47 RSSI; Strong Signal
./nettest.sh: line 668: -90: No such file or directory
 -98 RF Noise High
```

I wasn't able to reproduce this error.

**Comment by angela-d** [comment]
> I copied the default configuration into ~/.nettest/config.conf 

You shouldn't need to copy anything, that gets generated on first run.  (You can also delete ~/.nettest anytime you want to start fresh.)

Line 668:
```bash
if [ "$WifiNoise" < -90 ];
```
I'll fix this shortly and tag this issue when I push the commit, you should get a notification.  Please test it, when you can!
