### ISSUE TITLE
ping flags for macOS need to be updated

### ISSUE THREAD

**Issue by drjasonharrison** [angela-d/wifi-network-testing#3]
When using option 2 on macOS, I get this error

```
Testing Connection to Internet...
------------------------------------------------------------------------------
usage: ping [-AaDdfnoQqRrv] [-c count] [-G sweepmaxsize]
            [-g sweepminsize] [-h sweepincrsize] [-i wait]
            [-l preload] [-M mask | time] [-m ttl] [-p pattern]
            [-S src_addr] [-s packetsize] [-t timeout][-W waittime]
            [-z tos] host
       ping [-AaDdfLnoQqRrv] [-c count] [-I iface] [-i wait]
            [-l preload] [-M mask | time] [-m ttl] [-p pattern] [-S src_addr]
            [-s packetsize] [-T ttl] [-t timeout] [-W waittime]
            [-z tos] mcast-group
Apple specific options (to be specified before mcast-group or host like all options)
            -b boundif           # bind the socket to the interface
            -k traffic_class     # set traffic class socket option
            -K net_service_type  # set traffic class socket options
            -apple-connect       # call connect(2) in the socket
            -apple-time          # display current time
Connection is DOWN
```

adding at set -x to the script, it looks like $PINGPROTOCOL is empty, it's set to the empty string in my config,  and creating and empty argument:

```
+ pingOptions 9.9.9.9
+ '[' mac '!=' windows ']'
+ ping '' -c 3 -q 9.9.9.9
```

Unfortunately OSX doesn't have a -4 or -6 flag, one way to fix this would be to break out the mac vs linux options in the if statements, another would be to check if $PINGPROTOCOL is empty before including it in the command.

**Comment by angela-d** [comment]
Thanks for the report!

Please pull the latest version & test when you have a moment.
The [wiki options](https://github.com/angela-d/wifi-network-testing/wiki/Customizing) for protocol will persist, even if Mac doesn't support them.

Linux & Windows do, so I did a condition before any pings are called to pull the user preference.  If a user is on Mac and has `-6` in their config, it should switch to `ping6` for them.

Both Linux & Windows may also support `ping6`, but this was an afterthought as I was typing this reply.
Will probably clean up that condition in a future commit

The preference check should work as follows:
```bash
if [ "$OS"  == 'linux' ] || [ "$OS"  == 'windows' ] && [ "$PINGPROTOCOL"  == '-6' ];
```
- Switch to `ping -6`

```bash
elif [ "$OS"  == 'linux' ] || [ "$OS"  == 'windows' ] && [ "$PINGPROTOCOL"  == '-4' ];
```
- Switch to `ping -4`
- Debian Linux defaults to ipv6, so an override is necessary

```bash
elif [ "$OS"  == 'mac' ] && [ "$PINGPROTOCOL"  == '-6' ];
```
- Switch to `ping6`
- Support for Windows and Linux, can probably drop a line or two by merging, in the future

```bash
else
  PINGS='ping'
```
- Default to `ping` - Should fix the reported bug
