### ISSUE TITLE
On macOS mixed results with option 6, access point and wifi usage includes errors

### ISSUE THREAD

**Issue by drjasonharrison** [angela-d/wifi-network-testing#6]
Overall option 6 is working, but there are a few errors. I haven't looked at the code. Lines 969 and 972.

```
Option 6 selected
------------------------------------------------------------------------------
Checking Wifi...
------------------------------------------------------------------------------
Signal
 -52 RSSI; Strong Signal
 -96 RF Noise Acceptable
Access Point Details
 SSID:                Yassas2        
 Channel:             48             
 Radio:               5GHz           
 MAC:                 44:a5:6e:5a:be:73
       :              NETGEAR
------------------------------------------------------------------------------
Determining channel usage by array...
------------------------------------------------------------------------------
Sorted ascending by signal strength
BeeCee
 RSSID: 2.4G
./nettest.sh: line 969: [: 2.4G: integer expression expected
./nettest.sh: line 972: [: 2.4G: integer expression expected
 (far away; poorest signal)
 Channel: cc:be:59:1f:ea:75
 BSSID: -
--------
Brightside
 RSSID: -42
 (closest / loudest signal)
 Channel: 6,+1
 BSSID: 4a:a5:6e:5a:be:71
--------
Waterford
 RSSID: a8:4e:3f:78:03:28
./nettest.sh: line 969: [: a8:4e:3f:78:03:28: integer expression expected
./nettest.sh: line 972: [: a8:4e:3f:78:03:28: integer expression expected
 (far away; poorest signal)
 Channel: -85
 BSSID: 2.4
--------
TELUS3431-24G
 RSSID: -71
 (fairly close)
 Channel: 11
 BSSID: fc:2b:b2:e8:8f:e2
--------

...output truncated...
```

**Comment by angela-d** [comment]
Do you or any of your neighbors have spaces in the SSID name?

(check in your wifi GUI, not this script)

If so, this is a known bug, you can see it in my screenshot here: https://github.com/angela-d/wifi-network-testing/blob/master/img/test6-linux.png


Can you confirm whether or not this is similar to what you're seeing?

**Comment by drjasonharrison** [comment]
Some SSID's are blank or have spaces

**Comment by angela-d** [comment]
Yup that is what's causing that, it's a bug.
I usually have 0-1 SSID with spaces nearby, in the places I use this script, so I never rushed to fix it.

I'll prioritize it on my bugfixes now that someone else is running into it, too.

**Comment by angela-d** [comment]
This bug should be fixed, now.

May have possibly introduced a new bug, though.
I did have the intermittent appearance of: `grep (23) Failed writing body` during test 6 on a Mac - please report back if you find the same.

**Comment by angela-d** [comment]
The Failed writing body bug should be fixed; only encountered it in enterprise mode.
New enterprise bug mode remains, noted in [bug list](https://github.com/angela-d/wifi-network-testing/wiki/Known-Bugs/)

**Comment by drjasonharrison** [comment]
Looks like everything is working!
